name: Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -timeout 30s -v -race ./... 

    - name: Coverage
      env:
        COVERAGE_THRESHOLD: 90
      run: ./test.sh

    - name: Benchmark
      run: go test -benchmem -run=^$ -bench . ./...
